# Generated by Django 2.2 on 2021-05-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_shell_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='note'),
            preserve_default=False,
        ),
    ]
